/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.callcenter.login.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;


import com.callcenter.login.data.LoginDB;
import com.callcenter.login.form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-28-2009
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" scope="request" validate="true"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		LoginDB loginDB = new LoginDB();
		HttpSession session = request.getSession();
		String userName = loginForm.getUserName();
		String passWord = loginForm.getPassWord();
		 
		String forwardText = null;
	//	System.out.println("ipAddress : "+ipAddress);
		
		if(userName != "" || passWord != "") {
			loginForm = loginDB.checkLogin(userName, passWord);
			if(loginForm.isTrue()) {
					
					session.setAttribute("userName", userName);
					session.setAttribute("passWord", passWord);
					session.setAttribute("name", loginForm.getName());
					session.setAttribute("type", loginForm.getType());
					 
				//	session.setAttribute("actionDisabled", loginForm.isActionDisabled());
				//	session.setAttribute("actionDisabled", "true");
					forwardText = "success";
					
					List memberList = loginDB.MemberList("", "", "");
					request.setAttribute("memberList", memberList);
				 
					loginForm.reset();
			
			} else {
				request.setAttribute("error", "Username หรือ Password ไม่ถู�?ต้อง ");
				forwardText = "error";
			}
		} else {
			request.setAttribute("error", "โปรดระบุ Username �?ละ Password");
			forwardText = "error";
		}
		return mapping.findForward(forwardText);
	}
}