/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.callcenter.agent.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 18-06-2015
 * 
 * XDoclet definition:
 * @struts.form name="loginForm"
 */
public class MainAgentForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String fromDate;
	private String toDate;
	private String custID;
	private String custName;
	private String custAddr;
	private String custEmail;
	private String custDate;
	private String custType;
	private String period;
	private boolean isTrue;
	
	private String save = null;
	private String update = null;
	private String search = null;
	private String next = null;
	private String createCustomer = null;
	
	public MainAgentForm(){};
	public MainAgentForm (String custID, String custName, String custDate, String custType, String period){
		super();
		this.custID 	= custID;
		this.custName	= custName;
		this.custDate	= custDate;
		this.custType	= custType;
		this.period		= period;
}
	public void reset() {
		this.fromDate = "";
		this.toDate = "";
	}
	
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
	public String getFromDate() {
		return fromDate;
	}
	public void setFromDate(String fromDate) {
		this.fromDate = fromDate;
	}
	public String getToDate() {
		return toDate;
	}
	public void setToDate(String toDate) {
		this.toDate = toDate;
	}
	public String getCustID() {
		return custID;
	}
	public void setCustID(String custID) {
		this.custID = custID;
	}
	public String getCustName() {
		return custName;
	}
	public void setCustName(String custName) {
		this.custName = custName;
	}
	public String getCustAddr() {
		return custAddr;
	}
	public void setCustAddr(String custAddr) {
		this.custAddr = custAddr;
	}
	public String getCustEmail() {
		return custEmail;
	}
	public void setCustEmail(String custEmail) {
		this.custEmail = custEmail;
	}
	public String getCustDate() {
		return custDate;
	}
	public void setCustDate(String custDate) {
		this.custDate = custDate;
	}
	public String getCustType() {
		return custType;
	}
	public void setCustType(String custType) {
		this.custType = custType;
	}
	public boolean isTrue() {
		return isTrue;
	}
	public void setTrue(boolean isTrue) {
		this.isTrue = isTrue;
	}
	public String getSearch() {
		return search;
	}
	public void setSearch(String search) {
		this.search = search;
	}
	public String getPeriod() {
		return period;
	}
	public void setPeriod(String period) {
		this.period = period;
	}
	public String getNext() {
		return next;
	}
	public void setNext(String next) {
		this.next = next;
	}
	public String getSave() {
		return save;
	}
	public void setSave(String save) {
		this.save = save;
	}
	public String getUpdate() {
		return update;
	}
	public void setUpdate(String update) {
		this.update = update;
	}
	public String getCreateCustomer() {
		return createCustomer;
	}
	public void setCreateCustomer(String createCustomer) {
		this.createCustomer = createCustomer;
	}
	

}